-- 🧬 STUDIO AI FOUNDATION (AUTONOMOUS SIGNAL PATHS)
ALTER TABLE samples ADD COLUMN IF NOT EXISTS ai_mood TEXT;
ALTER TABLE samples ADD COLUMN IF NOT EXISTS ai_genre TEXT;
ALTER TABLE samples ADD COLUMN IF NOT EXISTS ai_description TEXT;
ALTER TABLE samples ADD COLUMN IF NOT EXISTS ai_vibe_score FLOAT DEFAULT 0.0;
ALTER TABLE samples ADD COLUMN IF NOT EXISTS ai_is_processed BOOLEAN DEFAULT FALSE;

-- AI ANALYTICS LOG (DIAGNOSTIC ARCHIVE)
CREATE TABLE IF NOT EXISTS ai_signal_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sample_id UUID REFERENCES samples(id) ON DELETE CASCADE,
    analysis_phase TEXT, -- 'INGESTION', 'RESONANCE', 'SMART_TAG'
    result_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
